# config/strategy.yml  (only show changed/important parts)
universe:
  indices: ["NIFTY50"]
  expiry_preference: "weekly_near"

expiry_rules:
  # Custom weekly expiry day as requested
  nifty_weekly_day: "TUESDAY"

execution:
  primary_broker: "angel_one"
  allow_market_if_slippage_ok: true
  max_retries: 1
